@startuml "Application-Overview"
!include skin.puml

component Scheduler
component Scraper
database Database
queue Queue

Database --> Scheduler: Get the searches from database
Scheduler -> Queue: Schedule the searches\ninto queue
Queue . Scraper: Listen the queue\nand the run scrapers
Scraper --> Database: Save the products in Database

@enduml