@startuml "skin-definition"
skinparam {
  Handwritten true
  Shadowing false

  BackgroundColor #ffffff
  DefaultFontColor #282a36
  ArrowFontColor #6272a4
  ArrowColor #282a36

  DatabaseBackgroundColor #ffffff
  ComponentBackgroundColor #ffffff
  QueueBackgroundColor #ffffff

  DatabaseBorderColor #282a36
  ComponentBorderColor #282a36
  QueueBorderColor #282a36
}
@enduml